### ISSUE TITLE
Import the dataset JSON and load into memory to show list views

### ISSUE THREAD

**Issue by teampolyglot** [learn-awesome/mobile-app#2]
The JSON will be periodically updated here: https://learnawesome-export.s3.us-east-2.amazonaws.com/dataset.json

The Job that generates this JSON is here: https://github.com/learn-awesome/learn/blob/master/lib/tasks/export.rake

**Comment by teampolyglot** [comment]
The domain model is basically this: 
![image](https://user-images.githubusercontent.com/51651338/93503895-57836300-f936-11ea-8ee7-31226654b147.png)

However, the exported JSON hides the abstraction of idea_sets. This will have to be solved when we implement "Related Items" feature in the app.

**Comment by teampolyglot** [comment]
Right now, the JSON is small enough (10 MB) that it can be loaded in RAM. Eventually, we will have to store it in database with indexing for good performance. This can be taken up as an enhancement much later.

**Comment by nileshtrivedi** [comment]
This is fixed in #14 by @cyber-venom003. Closing.
